#!/bin/sh
# Clean build artifacts not needed for the next build.
# Removes:
#   pkg/        wasm-pack output (regenerated by `wasm-pack build`)
#   target/     cargo build cache (debug/, release/, wasm32-unknown-unknown/)
#   .DS_Store   macOS junk, anywhere in the repo
# Keeps everything the next build needs: src/, js/, tests/, vendor/,
# Cargo.toml, Cargo.lock, build.sh, README.md.
set -e
cd "$(dirname "$0")"

rm -rf pkg target
find . -name '.DS_Store' -type f -delete

echo "cleaned: pkg/ target/ .DS_Store"
